import photo1 from "../images/photo1.jpeg";
import photo2 from "../images/photo2.jpeg";
import photo3 from "../images/photo3.jpeg";
import photo4 from "../images/photo4.jpeg";
import photo5 from "../images/photo5.jpeg";
import photo6 from "../images/photo6.jpeg";
import photo7 from "../images/photo7.jpeg";
import photo8 from "../images/photo8.jpeg";
import photo9 from "../images/photo9.jpeg";
import photo10 from "../images/photo10.jpeg";
export const imageArr = [
  {
    img: photo1,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo2,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo3,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo4,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo5,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo6,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo7,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo8,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo9,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
  {
    img: photo10,
    opacity: "100",
    sepia: "0",
    saturate: "100",
    hueRotate: "0",
    grayscale: "0",
    brightness: "100",
    contrast: "100",
    blur: "0",
  },
];
